version: '3'

services:
  web:
    build: .
    image: phpscrapyapp
    depends_on:
      - "db"
    ports:
      - "8080:80"

  db:
    image: mongo
    container_name: some-mongo
    ports:
      - "27017:27017"
